name: maxwell
description: "A Flutter project that simulated latex expressions."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.4.0
  flutter_math_fork: ^0.7.2
  icons_plus: ^5.0.0
  lottie: ^2.7.0
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/jsons/
    - assets/lotties/
